# Generated by Django 2.2.7 on 2019-11-15 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='token',
        ),
    ]
