# Generated by Django 2.2.4 on 2019-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20191021_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_items',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
